### ISSUE TITLE
Any plan to support bursting in the avalon MM VIP?

### ISSUE THREAD

**Issue by nathanaelhuffman** [UVVM/UVVM_All#28]
I have a need for that functionality and if there were plans for it to appear in the next release or near future, I might work on another area of the design rather than making a bursting VIP myself.

**Comment by UVVM** [comment]
Hi,
I am afraid this is not something we will be implementing in near future.
But, we would appreciate any contribution.

Best Regards
Marius


Fra: Nathanael Huffman [mailto:notifications@github.com]
Sendt: onsdag 13. september 2017 22.06
Til: UVVM/UVVM_All <UVVM_All@noreply.github.com>
Kopi: Subscribed <subscribed@noreply.github.com>
Emne: [UVVM/UVVM_All] Any plan to support bursting in the avalon MM VIP? (#28)


I have a need for that functionality and if there were plans for it to appear in the next release or near future, I might work on another area of the design rather than making a bursting VIP myself.
