### ISSUE TITLE
axialite read data

### ISSUE THREAD

**Issue by stfarley** [UVVM/UVVM_All#31]
Hello,

I can get axialite_read to function. It appears that the data read is not available to the test bench though. Is this intentional? I am guessing a new axilite_read function is required for this.

**Comment by UVVM** [comment]
Hi,
I’m not sure if I understand your question correctly, but you will need to include the package in your TB to use it.
For reading data you must use axilite_read().

Br.
Marius

Fra: stfarley [mailto:notifications@github.com]
Sendt: torsdag 21. september 2017 17.09
Til: UVVM/UVVM_All <UVVM_All@noreply.github.com>
Kopi: Subscribed <subscribed@noreply.github.com>
Emne: [UVVM/UVVM_All] axialite read data (#31)


Hello,

I can get axialite_read to function. It appears that the data read is not available to the test bench though. Is this intentional? I am guessing a new axilite_read function is required for this.
